### ISSUE TITLE
Doesn't open on Nspire CX CAS

### ISSUE THREAD

**Issue by TurboWafflz** [johannes-wolf/rpnspire#37]
When attempting to open the document on my TI-Nspire CX CAS, I get a message saying "An error was found in the format of this document". Is this only compatible with the CX II? I noticed all of the screenshots are on that device

![screenshot](https://user-images.githubusercontent.com/26664670/213589480-532ee7ec-ec03-4a91-805a-28466c262867.png)

**Comment by adriweb** [comment]
Which OS version are you using?

**Comment by TurboWafflz** [comment]
4.5.4.48, there is a slightly newer version available, but I don't want to upgrade until it's supported by ndless

**Comment by TurboWafflz** [comment]
Ahh, I think the problem is just user stupidity. I didn't realize that there were releases with actual tns files because Github defaulted to the tags page for some reason so I was using the tns directly in the repo (which I'm assuming is not actually the built program, if it is then something is still wrong). The latest release seems to actually work.

**Comment by johannes-wolf** [comment]
@TurboWafflz You are correct. The TNS in the repo (sadly) does not work.
I can upload a current release if you are interested?

**Comment by TurboWafflz** [comment]
I mean I don't really care that much now that I found the working version, you don't have to bother making a new release right now unless you want to. 
Unless it's somehow used in the build process, you might want to add the tns to the gitignore to reduce confusion.

**Comment by johannes-wolf** [comment]
Yes, I will remove it from the repo. It is generated by the build script (via Luna) but something is wrong, and it's always invalid.
