### ISSUE TITLE
Bug?/Feature request - Not possible to enter negative exponents using EE key

### ISSUE THREAD

**Issue by jimrustle** [johannes-wolf/rpnspire#41]
Pressing the (-) key causes the entire expression to be negated. This is contrary to usual HP RPN-style exponentiation, where the (-) key should only negate the input after the EE. I suppose you can work around this by pushing your signifcand to the stack first and then multiplying by your value after using the 10^x key.

Using rpn.tns from build #306 on a CXII CAS (OS 6.0.3.374).

**Comment by johannes-wolf** [comment]
Thank you for reporting.
Should be fixed (and also respect `-` (then non `(-)` version) and `+`) with commit cc0db1e.
