### ISSUE TITLE
Variables do not function

### ISSUE THREAD

**Issue by lordbagel42** [johannes-wolf/rpnspire#43]
I can't seem to do anything related to variables. It always either complains about it not being defined or, if I try to define it, shows "Internal Error" Error!!!

I do not have ndless installed and I am on version 5.3.2.129.

Thanks!

**Comment by johannes-wolf** [comment]
Can you explain what you mean? Like entering variables/pushing them on the stack?
Something like `x` <key>enter</key> gives you an error?

**Comment by lordbagel42** [comment]
That’s what I mean, yes. Sorry for explaining badly.

**Comment by johannes-wolf** [comment]
Did you build the .tns file yourself?

**Comment by lordbagel42** [comment]
I used both the latest Action listed in your repo along with one in my own GitHub fork

**Comment by johannes-wolf** [comment]
I am using OS 6.0.3.374, but it was working with an ndless OS I've had installed before (it was the latest ndless compatible version).

Have you installed the rpn.tns file in your `MyWidgets` directory?

**Comment by johannes-wolf** [comment]
I guess it is calling some lua API function that does not exist on 5.0.* OS. Maybe you can try running it in the debugger on your computer and set a breakpoint to check the error string?

**Comment by lordbagel42** [comment]
I'll try the debugger. I don't want to update in case ndless doesn't support a 6.0 version for a long time but might give up on that idea.

Do you have CAS?

**Comment by johannes-wolf** [comment]
Yes, I do have the red CX II-T CAS version.

**Comment by johannes-wolf** [comment]
It seems ndless does not support versions > 5.3. The reason I upgraded to 6 was that 5.3 has a bug that returns wrong pixel sizes when measuring text -- but that's not really a big deal.

**Comment by adriweb** [comment]
> 5.3 has a bug that returns wrong pixel sizes when measuring text -- but that's not really a big deal.

Can you give more details about this? Thanks

**Comment by johannes-wolf** [comment]
> > 5.3 has a bug that returns wrong pixel sizes when measuring text -- but that's not really a big deal.
> 
> Can you give more details about this? Thanks

It seems to be a bug in the TI API:
Calling `gc:text_width(...)` returns wrong sizes for long text. This prevents correct scrolling of the expression input of rpnspire on that OS.

**Comment by johannes-wolf** [comment]
Any update on this @lordbagel42?
