### ISSUE TITLE
Feature Request - Allow user to force the recieved answer in scientific/enginering notation when output is not big number

### ISSUE THREAD

**Issue by ODog2028** [johannes-wolf/rpnspire#44]
Hello! I would like the ability to force the recieved answer in scientific/enginering notation when the output is not a large number that needs to be approximated. I would also like to be able to change the number of significant digits in that output.

**Comment by johannes-wolf** [comment]
Can you give an example for some number please?

**Comment by Izzy129** [comment]
I'm thinking, if a result is something small like 4.125, they want it in scientific notation like 4.13x10^0 or 4.13E0 for 2 significant digits.
41.25 would be 4.13x10^1 or 4.13E1
412.5 would be 4.13x10^2 or 4.13E2
and so on.

**Comment by johannes-wolf** [comment]
Closing this issuer, as the author did not respond.

**Comment by johannes-wolf** [comment]
Hint: General formatting of the output can be done here: https://github.com/johannes-wolf/rpnspire/blob/1dd951af3c1d7d4b869718d5e06db7ef62764016/expressiontree.lua#L194
